#!/bin/dash

SSH_ADDRESS='login.cse.unsw.edu.au'

subject=$(pwd | grep -o -E "/[A-Z]{4}[0-9]{4}.*")

setup() {
	local zID
	read -p "Enter your zID (e.g. z1234567): " zID
	echo "zID: $zID" > ./.config
}

if [ ! -f "./.config" ]; then
    setup
fi
zID=$(sed -En "s/zID: +(z[0-9]{5,})/\1/p" ./.config)
if [ ! -n "$zID" ]; then
    rm "./.config"
    echo "Invalid zID in configuration. Rerun to configure"
    exit 1;
fi

connect() {
    commands="clear"
    if [ ! -z '$@' ]; then 
        commands="$commands; bash -c \"$@\""
    fi
    commands="$commands; bash"
    ssh -t "$zID@$SSH_ADDRESS" "$commands"
}


case "$1" in
    sync)
        dest="$3"
        [ -z $dest ] && dest="."
        rsync -az "$zID@$SSH_ADDRESS:./$2/" "$dest"
        ;;
    connect)
        clear
        connect
        ;;
    execute)
        shift 1
        connect "$@"
        ;;
    help)
        echo "Possible commands: "
        echo "\t- cselink sync <source directory> <destination ('.' if blank)>"
        echo "\t- cselink connect"
        echo "\t- cselink execute <commands>"
        ;;
    *)
        echo "Unrecognised command, try 'cselink help' to see available commands."
        exit 1
esac

exit 0;

