#!/bin/dash

SSH_ADDRESS='login.cse.unsw.edu.au'
CONFIG_FILE='./.cselinkconfig'
subject=$(pwd | grep -o -E "/[A-Z]{4}[0-9]{4}.*")

setup() {
	local zID
	read -p "Enter your zID (e.g. z1234567): " zID
	echo "zID: $zID" > "$CONFIG_FILE"
}

if [ ! -f "$CONFIG_FILE" ]; then
    setup
fi

zID=$(sed -En "s/zID: +(z[0-9]{5,})/\1/p" "$CONFIG_FILE")
if [ ! -n "$zID" ]; then
    rm "$CONFIG_FILE"
    echo "Invalid zID in configuration. Rerun to configure"
    exit 1;
fi

connect() {
    commands="clear"
    if [ ! -z '$@' ]; then 
        commands="$commands; bash -c \"$@\""
    fi
    commands="$commands; bash"
    ssh -t "$zID@$SSH_ADDRESS" "$commands"
}


case "$1" in
    pull)
        dest="$3"
        [ -z $dest ] && dest="."
        rsync -av "$zID@$SSH_ADDRESS:$2/" "$dest"
        ;;
    push)
        rsync -av "$2" "$zID@$SSH_ADDRESS:$3/"
        ;;
    connect)
        clear
        connect
        ;;
    execute)
        shift 1
        connect "$@"
        ;;
    help)
        echo "Possible commands: "
        echo "\t- cselink push <source> <remote destination>"
        echo "\t- cselink pull <remote source> <destination>"
        echo "\t- cselink connect"
        echo "\t- cselink execute <commands>"
        ;;
    *)
        echo "Unrecognised command, try 'cselink help' to see available commands."
        exit 1
esac

exit 0;

